### ISSUE TITLE
It doesn't work with my modeler

### ISSUE THREAD

**Issue by aisong** [camunda/camunda-modeler-linter-plugin#24]
## Camunda Modeler system information
 * Version: 4.12.0
 * Operating System: Mac OS 11.5.0 
 * Plugins: BPMN Linter
 * Execution Platform: BPMN - Camunda Cloud

It doesn't show any check result in the modeler.
<img width="983" alt="image" src="https://user-images.githubusercontent.com/8147898/162546032-c7ef859e-8753-4699-95b0-bf22e538f286.png">

And, when I click the toggle Linting menu,some errors was displayed:
`toggleLinting is not a registered action
    at ia (webpack:///node_modules/bpmn-js/node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:257:9)
    at ra.na.trigger (webpack:///node_modules/bpmn-js/node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:167:10)
    at trigger (webpack:///src/app/tabs/cloud-bpmn/BpmnEditor.js:529:40)
    at triggerAction (webpack:///src/app/tabs/MultiSheetTab.js:269:18)
    at triggerAction (webpack:///src/app/tabs/EditorTab.js:36:33)
    at triggerAction (webpack:///src/app/App.js:1782:15)
    at fn (webpack:///src/app/App.js:2250:19)
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/bundle.js:73:147880
    at exec (webpack:///src/app/AppParent.js:76:11) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
[Disable plug-ins (restarts the app)](https://github.com/camunda/camunda-modeler-linter-plugin/issues/new#) [ info ]`

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/8147898/162546240-d123fe48-39db-4074-8008-93ffe440b122.png">

What's wrong with me?

**Comment by pinussilvestrus** [comment]
You are using an older version of the Camunda Modeler (v4.12.0). Plugins for Camunda Cloud / Camunda Platform 8 are only supported beginning with version v5.0.0, which will be released tomorrow. 

Find some more context [in this issue](https://github.com/camunda/camunda-modeler/issues/2284).

**Comment by aisong** [comment]
OK,Thanks a lot.
